### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by AtheosCode** [dotsnav/dotsnav#13] opened 2022-02-18 02:46 UTC
![image](https://user-images.githubusercontent.com/11506195/154607661-3b8eeb8f-54e1-4519-bf27-555f01a2d7e5.png)
Erorr in 2020.3.28  Normal in 2020.3.25，It looks like a Unity modified IJobParallelForDefer

**Comment by bassmit** [comment] 2022-02-18 15:13
Hi, thanks for reporting, that's very annoying. Let me know if you find the cause, I'll try to look at it as soon as I can, but I don't know when that will be

**Comment by bassmit** [comment] 2022-03-27 15:11
this is fixed in version 0.2.1: upgrade lts to 2020.3.32f1 and packages to 0.50.0

**Closed by bassmit** 2022-03-27 15:11 UTC
